parent: "duvalhub/dummies-parent.yml"
app:
  version_control: maven
build:
  builder: maven
  builder_version: 3.9.12-eclipse-temurin-25-noble
  container: eclipse-temurin
  container_template: openjdk
  container_version: 25-jre-alpine
  destination: "target/*.jar"

deploy:
  database:
    enabled: true
  port: 8080
  platforms:
    dev:
      defaultHostname: true
    prod:
      host:
        url: swarmlocal.duvalhub.com
